description = "description receivers"
name = "test receiver"
id_sm = 0
ip_sm = ""
grpc_port = 50000
metric_port = 9902
nats_address = "nats://192.168.194.242:4222"
nats_topic = "navigation"
nats_timeout = 5
is_jetstream= true

[log_config]
log_level = "info"
log_file_path = "logs/receiver.log"
max_size = 100
max_backups = 3
max_age = 28
compress = true

[[receivers]]
id_receiver = 1
active = true
name = "Main Receiver"
port_receiver = 9500
protocol = "EGTS"
status = ""
description = "Primary data receiver"
connections_count = 0

[[receivers]]
id_receiver = 2
active = true
name = "Test Scenario Port"
port_receiver = 9501
protocol = "Arnavi"
status = "ok"
description = ""
connections_count = 0