grpc_port = 50051
metric_port = 9092
nats_address = "nats://localhost:4222"
nats_topic = "nav.data"
nats_timeout = 5

[log_config]
log_level = "info"
log_file_path = "logs/app.log"
max_size = 100
max_backups = 3
max_age = 28
compress = true

[[receivers]]
id_receiver = 1
id_sm = 1
active = false
name = "Main Receiver"
port_receiver = 8980
protocol = "EGTS"
status = "ok"
description = "Primary data receiver"
connections_count = 0

[[receivers]]
id_receiver = 2
id_sm = 1
active = true
name = "Backup Receiver"
port_receiver = 8981
protocol = "EGTS"
status = "ok"
description = "Backup data receiver"
connections_count = 5

[[receivers]]
id_receiver = 3
id_sm = 1
active = true
name = "Test Scenario Port"
port_receiver = 8082
protocol = "Arnavi"
status = "ok"
description = ""
connections_count = 0

[[receivers]]
id_receiver = 4
id_sm = 1
active = true
name = "Test Scenario Port"
port_receiver = 8081
protocol = "Arnavi"
status = "ok"
description = "This is a test scenario port"
connections_count = 0

