rest_port = 8082
metric_port = 9990

[cors]
allow_all_origins = true
#allow_origins = ["http://example.com", "http://localhost:8080"]
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
#allow_private_network = false
allow_headers = ["Origin", "Content-Type", "Authorization", "Accept", "User-Agent", "Cache-Control", "Pragma"]
allow_credentials = true
expose_headers = ["Content-Length"]
#allow_wildcard = true
#allow_browser_extensions = false
#custom_schemas = []
#allow_web_sockets = true
#allow_files = true
#options_response_status_code = 204

[[service_list]]
id_sm = 1
ip_sm = "localhost"
port_sm = 50000
name = "Прием данных"
type_sm = "RECEIVER"
ip_broker = "192.168.194.242"
port_broker = 1883
topic_broker = "nav.data"
active = true
status = "running"
description = "Primary service manager for sensor data"
log_level = "info"

[[service_list]]
id_sm = 2
ip_sm = "localhost"
port_sm = 50001
name = "Запись"
type_sm = "WRITER"
ip_broker = "192.168.194.242"
port_broker = 1883
topic_broker = "nav.data"
active = true
status = "running"
description = "Primary service manager for sensor data"
log_level = "info"
