rest_port = 8082
metric_port = 9990

[cors]
allow_all_origins = true
allow_origins = []
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_private_network = false
allow_headers = ["Origin", "Content-Type", "Authorization", "Accept", "User-Agent", "Cache-Control", "Pragma"]
allow_credentials = true
expose_headers = ["Content-Length"]
allow_wildcard = false
allow_browser_extensions = false
custom_schemas = []
allow_web_sockets = false
allow_files = false
options_response_status_code = 0

[log_config]
log_level = "info"
log_file_path = "logs/receiver.log"
max_size = 100
max_backups = 3
max_age = 28
compress = true

[[service_list]]
id_sm = 2
ip_sm = "localhost"
port_sm = 50052
name = "Отправка  данных"
type_sm = "RETRANSLATOR"
ip_broker = ""
port_broker = 0
topic_broker = ""
active = true
status = "online"
description = ""
log_level = ""

[[service_list]]
id_sm = 3
ip_sm = "localhost"
port_sm = 50000
name = "Прием данных"
type_sm = "RECEIVER"
ip_broker = "localhost"
port_broker = 4222
topic_broker = "nav.data"
active = true
status = "online"
description = ""
log_level = ""
