description = "Пример конфигурации для ControlRetranslator"
name = "retranslator-service"
id_sm = 1
ip_sm = ""
grpc_port = 50052
metric_port = 9092
# nats_address = "nats://localhost:4222"
# nats_topic = "nav.*"
# nats_timeout = 5
id_writer = 1
db_ip = "localhost"
db_port = 5432
db_name = "nsm"
db_user = "nsmsave"
db_pass = "rr1971"
db_table = "one.temp"

[log_config]
log_level = "info"
log_file_path = "logs/retranslator.log"
max_size = 100
max_backups = 3
max_age = 28
compress = true