id_sm = 1
description = "Сервис записи навигационных данных в БД"
name = "NavData Writer Service"
grpc_port = 9090
metric_port = 9091
nats_address = "nats://localhost:4222"
nats_topic = "navigation.data"

[log_config]
log_level = "info"
log_file = "/log/writer.log"
max_size = 100
max_age = 30
max_backups = 10

[[writers]]
description = "Основная база данных PostgreSQL"
name = "PostgreSQL Writer"
id_writer = 1
ip_db = "127.0.0.1"
port_db = 5432
name_db = "navdata"
login = "navuser"
passw_db = "navpass"
table_db = "navigation_points"

[[writers]]
description = "Резервная база данных"
name = "Backup MySQL Writer"
id_writer = 2
ip_db = "127.0.0.2"
port_db = 3306
name_db = "navbackup"
login = "backupuser"
passw_db = "backuppass"
table_db = "positions"