rest_port = 9400
metric_port = 9901

[cors]
allow_all_origins = true
allow_origins = []
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_private_network = false
allow_headers = ["Origin", "Content-Type", "Authorization", "Accept", "User-Agent", "Cache-Control", "Pragma"]
allow_credentials = true
expose_headers = ["Content-Length"]
allow_wildcard = false
allow_browser_extensions = false
custom_schemas = []
allow_web_sockets = false
allow_files = false
options_response_status_code = 0

