// Синтаксис Protocol Buffers v3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: manager.proto

// Пакет для Go

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdSm          int32                  `protobuf:"varint,1,opt,name=id_sm,json=idSm,proto3" json:"id_sm,omitempty"`                     // Уникальный идентификатор SM
	PortSm        int32                  `protobuf:"varint,2,opt,name=port_sm,json=portSm,proto3" json:"port_sm,omitempty"`               // Порт
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                  // Имя service
	IpBroker      string                 `protobuf:"bytes,4,opt,name=ip_broker,json=ipBroker,proto3" json:"ip_broker,omitempty"`          // IP адрес NATS
	PortBroker    int32                  `protobuf:"varint,5,opt,name=port_broker,json=portBroker,proto3" json:"port_broker,omitempty"`   // Номер порта NATS
	TopicBroker   string                 `protobuf:"bytes,6,opt,name=topic_broker,json=topicBroker,proto3" json:"topic_broker,omitempty"` // топик NATS
	IpSm          string                 `protobuf:"bytes,7,opt,name=ip_sm,json=ipSm,proto3" json:"ip_sm,omitempty"`                      // IP адрес receiver
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`                             // Активен ли
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                              // Статус
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`                   // Описание
	LogLevel      string                 `protobuf:"bytes,11,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`         // Уровень логирования
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDefinition) Reset() {
	*x = ServiceDefinition{}
	mi := &file_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDefinition) ProtoMessage() {}

func (x *ServiceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDefinition.ProtoReflect.Descriptor instead.
func (*ServiceDefinition) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceDefinition) GetIdSm() int32 {
	if x != nil {
		return x.IdSm
	}
	return 0
}

func (x *ServiceDefinition) GetPortSm() int32 {
	if x != nil {
		return x.PortSm
	}
	return 0
}

func (x *ServiceDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceDefinition) GetIpBroker() string {
	if x != nil {
		return x.IpBroker
	}
	return ""
}

func (x *ServiceDefinition) GetPortBroker() int32 {
	if x != nil {
		return x.PortBroker
	}
	return 0
}

func (x *ServiceDefinition) GetTopicBroker() string {
	if x != nil {
		return x.TopicBroker
	}
	return ""
}

func (x *ServiceDefinition) GetIpSm() string {
	if x != nil {
		return x.IpSm
	}
	return ""
}

func (x *ServiceDefinition) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ServiceDefinition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceDefinition) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type ServiceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdSm          int32                  `protobuf:"varint,1,opt,name=id_sm,json=idSm,proto3" json:"id_sm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceId) Reset() {
	*x = ServiceId{}
	mi := &file_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceId) ProtoMessage() {}

func (x *ServiceId) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceId.ProtoReflect.Descriptor instead.
func (*ServiceId) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceId) GetIdSm() int32 {
	if x != nil {
		return x.IdSm
	}
	return 0
}

type ChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Описание результата или ошибки
	Service       *ServiceDefinition     `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeResponse) Reset() {
	*x = ChangeResponse{}
	mi := &file_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeResponse) ProtoMessage() {}

func (x *ChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeResponse.ProtoReflect.Descriptor instead.
func (*ChangeResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChangeResponse) GetService() *ServiceDefinition {
	if x != nil {
		return x.Service
	}
	return nil
}

var File_manager_proto protoreflect.FileDescriptor

const file_manager_proto_rawDesc = "" +
	"\n" +
	"\rmanager.proto\x12\x05proto\x1a\rservice.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xba\x02\n" +
	"\x11ServiceDefinition\x12\x13\n" +
	"\x05id_sm\x18\x01 \x01(\x05R\x04idSm\x12\x17\n" +
	"\aport_sm\x18\x02 \x01(\x05R\x06portSm\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tip_broker\x18\x04 \x01(\tR\bipBroker\x12\x1f\n" +
	"\vport_broker\x18\x05 \x01(\x05R\n" +
	"portBroker\x12!\n" +
	"\ftopic_broker\x18\x06 \x01(\tR\vtopicBroker\x12\x13\n" +
	"\x05ip_sm\x18\a \x01(\tR\x04ipSm\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1b\n" +
	"\tlog_level\x18\v \x01(\tR\blogLevel\" \n" +
	"\tServiceId\x12\x13\n" +
	"\x05id_sm\x18\x01 \x01(\x05R\x04idSm\"x\n" +
	"\x0eChangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\aservice\x18\x03 \x01(\v2\x18.proto.ServiceDefinitionR\aservice2\xc2\x02\n" +
	"\aManager\x12?\n" +
	"\vGetServices\x12\x16.google.protobuf.Empty\x1a\x18.proto.ServiceDefinition\x128\n" +
	"\n" +
	"GetService\x12\x10.proto.ServiceId\x1a\x18.proto.ServiceDefinition\x12@\n" +
	"\rCreateService\x12\x18.proto.ServiceDefinition\x1a\x15.proto.ChangeResponse\x12@\n" +
	"\rUpdateService\x12\x18.proto.ServiceDefinition\x1a\x15.proto.ChangeResponse\x128\n" +
	"\rDeleteService\x12\x10.proto.ServiceId\x1a\x15.proto.ChangeResponseB\x12Z\x10NavControl/protob\x06proto3"

var (
	file_manager_proto_rawDescOnce sync.Once
	file_manager_proto_rawDescData []byte
)

func file_manager_proto_rawDescGZIP() []byte {
	file_manager_proto_rawDescOnce.Do(func() {
		file_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_proto_rawDesc), len(file_manager_proto_rawDesc)))
	})
	return file_manager_proto_rawDescData
}

var file_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_manager_proto_goTypes = []any{
	(*ServiceDefinition)(nil), // 0: proto.ServiceDefinition
	(*ServiceId)(nil),         // 1: proto.ServiceId
	(*ChangeResponse)(nil),    // 2: proto.ChangeResponse
	(*empty.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_manager_proto_depIdxs = []int32{
	0, // 0: proto.ChangeResponse.service:type_name -> proto.ServiceDefinition
	3, // 1: proto.Manager.GetServices:input_type -> google.protobuf.Empty
	1, // 2: proto.Manager.GetService:input_type -> proto.ServiceId
	0, // 3: proto.Manager.CreateService:input_type -> proto.ServiceDefinition
	0, // 4: proto.Manager.UpdateService:input_type -> proto.ServiceDefinition
	1, // 5: proto.Manager.DeleteService:input_type -> proto.ServiceId
	0, // 6: proto.Manager.GetServices:output_type -> proto.ServiceDefinition
	0, // 7: proto.Manager.GetService:output_type -> proto.ServiceDefinition
	2, // 8: proto.Manager.CreateService:output_type -> proto.ChangeResponse
	2, // 9: proto.Manager.UpdateService:output_type -> proto.ChangeResponse
	2, // 10: proto.Manager.DeleteService:output_type -> proto.ChangeResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_manager_proto_init() }
func file_manager_proto_init() {
	if File_manager_proto != nil {
		return
	}
	file_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_proto_rawDesc), len(file_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_proto_goTypes,
		DependencyIndexes: file_manager_proto_depIdxs,
		MessageInfos:      file_manager_proto_msgTypes,
	}.Build()
	File_manager_proto = out.File
	file_manager_proto_goTypes = nil
	file_manager_proto_depIdxs = nil
}
