// Синтаксис Protocol Buffers v3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: retranslator.proto

// Пакет для Go

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           int32                  `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Imei          string                 `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumDevice) Reset() {
	*x = NumDevice{}
	mi := &file_retranslator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumDevice) ProtoMessage() {}

func (x *NumDevice) ProtoReflect() protoreflect.Message {
	mi := &file_retranslator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumDevice.ProtoReflect.Descriptor instead.
func (*NumDevice) Descriptor() ([]byte, []int) {
	return file_retranslator_proto_rawDescGZIP(), []int{0}
}

func (x *NumDevice) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *NumDevice) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdDevice      int32                  `protobuf:"varint,1,opt,name=id_device,json=idDevice,proto3" json:"id_device,omitempty"`
	NumberDevice  *NumDevice             `protobuf:"bytes,2,opt,name=number_device,json=numberDevice,proto3" json:"number_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_retranslator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_retranslator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_retranslator_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetIdDevice() int32 {
	if x != nil {
		return x.IdDevice
	}
	return 0
}

func (x *Device) GetNumberDevice() *NumDevice {
	if x != nil {
		return x.NumberDevice
	}
	return nil
}

type Devices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListDevice    []*Device              `protobuf:"bytes,1,rep,name=list_device,json=listDevice,proto3" json:"list_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Devices) Reset() {
	*x = Devices{}
	mi := &file_retranslator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Devices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devices) ProtoMessage() {}

func (x *Devices) ProtoReflect() protoreflect.Message {
	mi := &file_retranslator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devices.ProtoReflect.Descriptor instead.
func (*Devices) Descriptor() ([]byte, []int) {
	return file_retranslator_proto_rawDescGZIP(), []int{2}
}

func (x *Devices) GetListDevice() []*Device {
	if x != nil {
		return x.ListDevice
	}
	return nil
}

type SetClient struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdRetranslator int32                  `protobuf:"varint,1,opt,name=id_retranslator,json=idRetranslator,proto3" json:"id_retranslator,omitempty"`
	IdSm           int32                  `protobuf:"varint,2,opt,name=id_sm,json=idSm,proto3" json:"id_sm,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetClient) Reset() {
	*x = SetClient{}
	mi := &file_retranslator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClient) ProtoMessage() {}

func (x *SetClient) ProtoReflect() protoreflect.Message {
	mi := &file_retranslator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClient.ProtoReflect.Descriptor instead.
func (*SetClient) Descriptor() ([]byte, []int) {
	return file_retranslator_proto_rawDescGZIP(), []int{3}
}

func (x *SetClient) GetIdRetranslator() int32 {
	if x != nil {
		return x.IdRetranslator
	}
	return 0
}

func (x *SetClient) GetIdSm() int32 {
	if x != nil {
		return x.IdSm
	}
	return 0
}

type Client struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdRetranslator int32                  `protobuf:"varint,1,opt,name=id_retranslator,json=idRetranslator,proto3" json:"id_retranslator,omitempty"`
	IdSm           int32                  `protobuf:"varint,2,opt,name=id_sm,json=idSm,proto3" json:"id_sm,omitempty"`
	IpClient       string                 `protobuf:"bytes,3,opt,name=ip_client,json=ipClient,proto3" json:"ip_client,omitempty"`
	PortClient     int32                  `protobuf:"varint,4,opt,name=port_client,json=portClient,proto3" json:"port_client,omitempty"`
	Protocol       string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	TimeStart      int32                  `protobuf:"varint,6,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	Sensors        []string               `protobuf:"bytes,7,rep,name=sensors,proto3" json:"sensors,omitempty"`
	DeviceList     []int32                `protobuf:"varint,8,rep,packed,name=device_list,json=deviceList,proto3" json:"device_list,omitempty"`
	Name           string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	IsActive       bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Description    string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_retranslator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_retranslator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_retranslator_proto_rawDescGZIP(), []int{4}
}

func (x *Client) GetIdRetranslator() int32 {
	if x != nil {
		return x.IdRetranslator
	}
	return 0
}

func (x *Client) GetIdSm() int32 {
	if x != nil {
		return x.IdSm
	}
	return 0
}

func (x *Client) GetIpClient() string {
	if x != nil {
		return x.IpClient
	}
	return ""
}

func (x *Client) GetPortClient() int32 {
	if x != nil {
		return x.PortClient
	}
	return 0
}

func (x *Client) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Client) GetTimeStart() int32 {
	if x != nil {
		return x.TimeStart
	}
	return 0
}

func (x *Client) GetSensors() []string {
	if x != nil {
		return x.Sensors
	}
	return nil
}

func (x *Client) GetDeviceList() []int32 {
	if x != nil {
		return x.DeviceList
	}
	return nil
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Client) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Client) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Clients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clients) Reset() {
	*x = Clients{}
	mi := &file_retranslator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clients) ProtoMessage() {}

func (x *Clients) ProtoReflect() protoreflect.Message {
	mi := &file_retranslator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clients.ProtoReflect.Descriptor instead.
func (*Clients) Descriptor() ([]byte, []int) {
	return file_retranslator_proto_rawDescGZIP(), []int{5}
}

func (x *Clients) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

var File_retranslator_proto protoreflect.FileDescriptor

const file_retranslator_proto_rawDesc = "" +
	"\n" +
	"\x12retranslator.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"1\n" +
	"\tNumDevice\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\x05R\x03tid\x12\x12\n" +
	"\x04imei\x18\x02 \x01(\tR\x04imei\"\\\n" +
	"\x06Device\x12\x1b\n" +
	"\tid_device\x18\x01 \x01(\x05R\bidDevice\x125\n" +
	"\rnumber_device\x18\x02 \x01(\v2\x10.proto.NumDeviceR\fnumberDevice\"9\n" +
	"\aDevices\x12.\n" +
	"\vlist_device\x18\x01 \x03(\v2\r.proto.DeviceR\n" +
	"listDevice\"I\n" +
	"\tSetClient\x12'\n" +
	"\x0fid_retranslator\x18\x01 \x01(\x05R\x0eidRetranslator\x12\x13\n" +
	"\x05id_sm\x18\x02 \x01(\x05R\x04idSm\"\xe5\x02\n" +
	"\x06Client\x12'\n" +
	"\x0fid_retranslator\x18\x01 \x01(\x05R\x0eidRetranslator\x12\x13\n" +
	"\x05id_sm\x18\x02 \x01(\x05R\x04idSm\x12\x1b\n" +
	"\tip_client\x18\x03 \x01(\tR\bipClient\x12\x1f\n" +
	"\vport_client\x18\x04 \x01(\x05R\n" +
	"portClient\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"time_start\x18\x06 \x01(\x05R\ttimeStart\x12\x18\n" +
	"\asensors\x18\a \x03(\tR\asensors\x12\x1f\n" +
	"\vdevice_list\x18\b \x03(\x05R\n" +
	"deviceList\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\"2\n" +
	"\aClients\x12'\n" +
	"\aclients\x18\x01 \x03(\v2\r.proto.ClientR\aclients2\xe2\x02\n" +
	"\x13RetranslatorControl\x12)\n" +
	"\tAddClient\x12\r.proto.Client\x1a\r.proto.Client\x12,\n" +
	"\fUpdateClient\x12\r.proto.Client\x1a\r.proto.Client\x124\n" +
	"\n" +
	"ListClient\x12\x16.google.protobuf.Empty\x1a\x0e.proto.Clients\x12+\n" +
	"\bUpClient\x12\x10.proto.SetClient\x1a\r.proto.Client\x12-\n" +
	"\n" +
	"DownClient\x12\x10.proto.SetClient\x1a\r.proto.Client\x12/\n" +
	"\fDeleteClient\x12\x10.proto.SetClient\x1a\r.proto.Client\x12/\n" +
	"\vListDevices\x12\x10.proto.SetClient\x1a\x0e.proto.DevicesB\x12Z\x10NavControl/protob\x06proto3"

var (
	file_retranslator_proto_rawDescOnce sync.Once
	file_retranslator_proto_rawDescData []byte
)

func file_retranslator_proto_rawDescGZIP() []byte {
	file_retranslator_proto_rawDescOnce.Do(func() {
		file_retranslator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_retranslator_proto_rawDesc), len(file_retranslator_proto_rawDesc)))
	})
	return file_retranslator_proto_rawDescData
}

var file_retranslator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_retranslator_proto_goTypes = []any{
	(*NumDevice)(nil),   // 0: proto.NumDevice
	(*Device)(nil),      // 1: proto.Device
	(*Devices)(nil),     // 2: proto.Devices
	(*SetClient)(nil),   // 3: proto.SetClient
	(*Client)(nil),      // 4: proto.Client
	(*Clients)(nil),     // 5: proto.Clients
	(*empty.Empty)(nil), // 6: google.protobuf.Empty
}
var file_retranslator_proto_depIdxs = []int32{
	0,  // 0: proto.Device.number_device:type_name -> proto.NumDevice
	1,  // 1: proto.Devices.list_device:type_name -> proto.Device
	4,  // 2: proto.Clients.clients:type_name -> proto.Client
	4,  // 3: proto.RetranslatorControl.AddClient:input_type -> proto.Client
	4,  // 4: proto.RetranslatorControl.UpdateClient:input_type -> proto.Client
	6,  // 5: proto.RetranslatorControl.ListClient:input_type -> google.protobuf.Empty
	3,  // 6: proto.RetranslatorControl.UpClient:input_type -> proto.SetClient
	3,  // 7: proto.RetranslatorControl.DownClient:input_type -> proto.SetClient
	3,  // 8: proto.RetranslatorControl.DeleteClient:input_type -> proto.SetClient
	3,  // 9: proto.RetranslatorControl.ListDevices:input_type -> proto.SetClient
	4,  // 10: proto.RetranslatorControl.AddClient:output_type -> proto.Client
	4,  // 11: proto.RetranslatorControl.UpdateClient:output_type -> proto.Client
	5,  // 12: proto.RetranslatorControl.ListClient:output_type -> proto.Clients
	4,  // 13: proto.RetranslatorControl.UpClient:output_type -> proto.Client
	4,  // 14: proto.RetranslatorControl.DownClient:output_type -> proto.Client
	4,  // 15: proto.RetranslatorControl.DeleteClient:output_type -> proto.Client
	2,  // 16: proto.RetranslatorControl.ListDevices:output_type -> proto.Devices
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_retranslator_proto_init() }
func file_retranslator_proto_init() {
	if File_retranslator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_retranslator_proto_rawDesc), len(file_retranslator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_retranslator_proto_goTypes,
		DependencyIndexes: file_retranslator_proto_depIdxs,
		MessageInfos:      file_retranslator_proto_msgTypes,
	}.Build()
	File_retranslator_proto = out.File
	file_retranslator_proto_goTypes = nil
	file_retranslator_proto_depIdxs = nil
}
