// Синтаксис Protocol Buffers v3

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: write.proto

// Пакет для Go

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WriteControl_ListWrite_FullMethodName = "/proto.WriteControl/ListWrite"
)

// WriteControlClient is the client API for WriteControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WriteControlClient interface {
	ListWrite(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetWrite, error)
}

type writeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewWriteControlClient(cc grpc.ClientConnInterface) WriteControlClient {
	return &writeControlClient{cc}
}

func (c *writeControlClient) ListWrite(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RetWrite, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetWrite)
	err := c.cc.Invoke(ctx, WriteControl_ListWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriteControlServer is the server API for WriteControl service.
// All implementations must embed UnimplementedWriteControlServer
// for forward compatibility.
type WriteControlServer interface {
	ListWrite(context.Context, *empty.Empty) (*RetWrite, error)
	mustEmbedUnimplementedWriteControlServer()
}

// UnimplementedWriteControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWriteControlServer struct{}

func (UnimplementedWriteControlServer) ListWrite(context.Context, *empty.Empty) (*RetWrite, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWrite not implemented")
}
func (UnimplementedWriteControlServer) mustEmbedUnimplementedWriteControlServer() {}
func (UnimplementedWriteControlServer) testEmbeddedByValue()                      {}

// UnsafeWriteControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WriteControlServer will
// result in compilation errors.
type UnsafeWriteControlServer interface {
	mustEmbedUnimplementedWriteControlServer()
}

func RegisterWriteControlServer(s grpc.ServiceRegistrar, srv WriteControlServer) {
	// If the following call pancis, it indicates UnimplementedWriteControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WriteControl_ServiceDesc, srv)
}

func _WriteControl_ListWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteControlServer).ListWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteControl_ListWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteControlServer).ListWrite(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WriteControl_ServiceDesc is the grpc.ServiceDesc for WriteControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WriteControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WriteControl",
	HandlerType: (*WriteControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWrite",
			Handler:    _WriteControl_ListWrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "write.proto",
}
