// Синтаксис Protocol Buffers v3

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: write.proto

// Пакет для Go

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WriteControl_ListWrites_FullMethodName  = "/proto.WriteControl/ListWrites"
	WriteControl_AddWrite_FullMethodName    = "/proto.WriteControl/AddWrite"
	WriteControl_DeleteWrite_FullMethodName = "/proto.WriteControl/DeleteWrite"
	WriteControl_DownWrite_FullMethodName   = "/proto.WriteControl/DownWrite"
	WriteControl_UpWrite_FullMethodName     = "/proto.WriteControl/UpWrite"
)

// WriteControlClient is the client API for WriteControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WriteControlClient interface {
	ListWrites(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RetWrite, error)
	AddWrite(ctx context.Context, in *WriteService, opts ...grpc.CallOption) (*WriteService, error)
	DeleteWrite(ctx context.Context, in *WriteService, opts ...grpc.CallOption) (*WriteService, error)
	DownWrite(ctx context.Context, in *SetWrite, opts ...grpc.CallOption) (*WriteService, error)
	UpWrite(ctx context.Context, in *SetWrite, opts ...grpc.CallOption) (*WriteService, error)
}

type writeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewWriteControlClient(cc grpc.ClientConnInterface) WriteControlClient {
	return &writeControlClient{cc}
}

func (c *writeControlClient) ListWrites(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RetWrite, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetWrite)
	err := c.cc.Invoke(ctx, WriteControl_ListWrites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeControlClient) AddWrite(ctx context.Context, in *WriteService, opts ...grpc.CallOption) (*WriteService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteService)
	err := c.cc.Invoke(ctx, WriteControl_AddWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeControlClient) DeleteWrite(ctx context.Context, in *WriteService, opts ...grpc.CallOption) (*WriteService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteService)
	err := c.cc.Invoke(ctx, WriteControl_DeleteWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeControlClient) DownWrite(ctx context.Context, in *SetWrite, opts ...grpc.CallOption) (*WriteService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteService)
	err := c.cc.Invoke(ctx, WriteControl_DownWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *writeControlClient) UpWrite(ctx context.Context, in *SetWrite, opts ...grpc.CallOption) (*WriteService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteService)
	err := c.cc.Invoke(ctx, WriteControl_UpWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriteControlServer is the server API for WriteControl service.
// All implementations must embed UnimplementedWriteControlServer
// for forward compatibility.
type WriteControlServer interface {
	ListWrites(context.Context, *emptypb.Empty) (*RetWrite, error)
	AddWrite(context.Context, *WriteService) (*WriteService, error)
	DeleteWrite(context.Context, *WriteService) (*WriteService, error)
	DownWrite(context.Context, *SetWrite) (*WriteService, error)
	UpWrite(context.Context, *SetWrite) (*WriteService, error)
	mustEmbedUnimplementedWriteControlServer()
}

// UnimplementedWriteControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWriteControlServer struct{}

func (UnimplementedWriteControlServer) ListWrites(context.Context, *emptypb.Empty) (*RetWrite, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWrites not implemented")
}
func (UnimplementedWriteControlServer) AddWrite(context.Context, *WriteService) (*WriteService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWrite not implemented")
}
func (UnimplementedWriteControlServer) DeleteWrite(context.Context, *WriteService) (*WriteService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWrite not implemented")
}
func (UnimplementedWriteControlServer) DownWrite(context.Context, *SetWrite) (*WriteService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownWrite not implemented")
}
func (UnimplementedWriteControlServer) UpWrite(context.Context, *SetWrite) (*WriteService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpWrite not implemented")
}
func (UnimplementedWriteControlServer) mustEmbedUnimplementedWriteControlServer() {}
func (UnimplementedWriteControlServer) testEmbeddedByValue()                      {}

// UnsafeWriteControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WriteControlServer will
// result in compilation errors.
type UnsafeWriteControlServer interface {
	mustEmbedUnimplementedWriteControlServer()
}

func RegisterWriteControlServer(s grpc.ServiceRegistrar, srv WriteControlServer) {
	// If the following call pancis, it indicates UnimplementedWriteControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WriteControl_ServiceDesc, srv)
}

func _WriteControl_ListWrites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteControlServer).ListWrites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteControl_ListWrites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteControlServer).ListWrites(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteControl_AddWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteControlServer).AddWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteControl_AddWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteControlServer).AddWrite(ctx, req.(*WriteService))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteControl_DeleteWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteControlServer).DeleteWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteControl_DeleteWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteControlServer).DeleteWrite(ctx, req.(*WriteService))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteControl_DownWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWrite)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteControlServer).DownWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteControl_DownWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteControlServer).DownWrite(ctx, req.(*SetWrite))
	}
	return interceptor(ctx, in, info, handler)
}

func _WriteControl_UpWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWrite)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteControlServer).UpWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteControl_UpWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteControlServer).UpWrite(ctx, req.(*SetWrite))
	}
	return interceptor(ctx, in, info, handler)
}

// WriteControl_ServiceDesc is the grpc.ServiceDesc for WriteControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WriteControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WriteControl",
	HandlerType: (*WriteControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWrites",
			Handler:    _WriteControl_ListWrites_Handler,
		},
		{
			MethodName: "AddWrite",
			Handler:    _WriteControl_AddWrite_Handler,
		},
		{
			MethodName: "DeleteWrite",
			Handler:    _WriteControl_DeleteWrite_Handler,
		},
		{
			MethodName: "DownWrite",
			Handler:    _WriteControl_DownWrite_Handler,
		},
		{
			MethodName: "UpWrite",
			Handler:    _WriteControl_UpWrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "write.proto",
}
