// Синтаксис Protocol Buffers v3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: write.proto

// Пакет для Go

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListWrite     []*WriteService        `protobuf:"bytes,1,rep,name=list_write,json=listWrite,proto3" json:"list_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetWrite) Reset() {
	*x = RetWrite{}
	mi := &file_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetWrite) ProtoMessage() {}

func (x *RetWrite) ProtoReflect() protoreflect.Message {
	mi := &file_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetWrite.ProtoReflect.Descriptor instead.
func (*RetWrite) Descriptor() ([]byte, []int) {
	return file_write_proto_rawDescGZIP(), []int{0}
}

func (x *RetWrite) GetListWrite() []*WriteService {
	if x != nil {
		return x.ListWrite
	}
	return nil
}

type WriteService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdWriter      int32                  `protobuf:"varint,1,opt,name=id_writer,json=idWriter,proto3" json:"id_writer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteService) Reset() {
	*x = WriteService{}
	mi := &file_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteService) ProtoMessage() {}

func (x *WriteService) ProtoReflect() protoreflect.Message {
	mi := &file_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteService.ProtoReflect.Descriptor instead.
func (*WriteService) Descriptor() ([]byte, []int) {
	return file_write_proto_rawDescGZIP(), []int{1}
}

func (x *WriteService) GetIdWriter() int32 {
	if x != nil {
		return x.IdWriter
	}
	return 0
}

var File_write_proto protoreflect.FileDescriptor

const file_write_proto_rawDesc = "" +
	"\n" +
	"\vwrite.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	"\bRetWrite\x122\n" +
	"\n" +
	"list_write\x18\x01 \x03(\v2\x13.proto.WriteServiceR\tlistWrite\"+\n" +
	"\fWriteService\x12\x1b\n" +
	"\tid_writer\x18\x01 \x01(\x05R\bidWriter2D\n" +
	"\fWriteControl\x124\n" +
	"\tListWrite\x12\x16.google.protobuf.Empty\x1a\x0f.proto.RetWriteB\x12Z\x10NavControl/protob\x06proto3"

var (
	file_write_proto_rawDescOnce sync.Once
	file_write_proto_rawDescData []byte
)

func file_write_proto_rawDescGZIP() []byte {
	file_write_proto_rawDescOnce.Do(func() {
		file_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_write_proto_rawDesc), len(file_write_proto_rawDesc)))
	})
	return file_write_proto_rawDescData
}

var file_write_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_write_proto_goTypes = []any{
	(*RetWrite)(nil),     // 0: proto.RetWrite
	(*WriteService)(nil), // 1: proto.WriteService
	(*empty.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_write_proto_depIdxs = []int32{
	1, // 0: proto.RetWrite.list_write:type_name -> proto.WriteService
	2, // 1: proto.WriteControl.ListWrite:input_type -> google.protobuf.Empty
	0, // 2: proto.WriteControl.ListWrite:output_type -> proto.RetWrite
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_write_proto_init() }
func file_write_proto_init() {
	if File_write_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_write_proto_rawDesc), len(file_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_write_proto_goTypes,
		DependencyIndexes: file_write_proto_depIdxs,
		MessageInfos:      file_write_proto_msgTypes,
	}.Build()
	File_write_proto = out.File
	file_write_proto_goTypes = nil
	file_write_proto_depIdxs = nil
}
