// Синтаксис Protocol Buffers v3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: write.proto

// Пакет для Go

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdWriter      int32                  `protobuf:"varint,1,opt,name=id_writer,json=idWriter,proto3" json:"id_writer,omitempty"`
	IdSm          int32                  `protobuf:"varint,2,opt,name=id_sm,json=idSm,proto3" json:"id_sm,omitempty"`
	IpDb          string                 `protobuf:"bytes,3,opt,name=ip_db,json=ipDb,proto3" json:"ip_db,omitempty"`
	PortDb        int32                  `protobuf:"varint,4,opt,name=port_db,json=portDb,proto3" json:"port_db,omitempty"`
	DbName        string                 `protobuf:"bytes,5,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	DbTable       string                 `protobuf:"bytes,6,opt,name=db_table,json=dbTable,proto3" json:"db_table,omitempty"`
	Login         string                 `protobuf:"bytes,7,opt,name=login,proto3" json:"login,omitempty"`
	Passw         string                 `protobuf:"bytes,8,opt,name=passw,proto3" json:"passw,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
	Description   string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteService) Reset() {
	*x = WriteService{}
	mi := &file_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteService) ProtoMessage() {}

func (x *WriteService) ProtoReflect() protoreflect.Message {
	mi := &file_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteService.ProtoReflect.Descriptor instead.
func (*WriteService) Descriptor() ([]byte, []int) {
	return file_write_proto_rawDescGZIP(), []int{0}
}

func (x *WriteService) GetIdWriter() int32 {
	if x != nil {
		return x.IdWriter
	}
	return 0
}

func (x *WriteService) GetIdSm() int32 {
	if x != nil {
		return x.IdSm
	}
	return 0
}

func (x *WriteService) GetIpDb() string {
	if x != nil {
		return x.IpDb
	}
	return ""
}

func (x *WriteService) GetPortDb() int32 {
	if x != nil {
		return x.PortDb
	}
	return 0
}

func (x *WriteService) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *WriteService) GetDbTable() string {
	if x != nil {
		return x.DbTable
	}
	return ""
}

func (x *WriteService) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *WriteService) GetPassw() string {
	if x != nil {
		return x.Passw
	}
	return ""
}

func (x *WriteService) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WriteService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WriteService) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *WriteService) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RetWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListWrite     []*WriteService        `protobuf:"bytes,1,rep,name=list_write,json=listWrite,proto3" json:"list_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetWrite) Reset() {
	*x = RetWrite{}
	mi := &file_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetWrite) ProtoMessage() {}

func (x *RetWrite) ProtoReflect() protoreflect.Message {
	mi := &file_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetWrite.ProtoReflect.Descriptor instead.
func (*RetWrite) Descriptor() ([]byte, []int) {
	return file_write_proto_rawDescGZIP(), []int{1}
}

func (x *RetWrite) GetListWrite() []*WriteService {
	if x != nil {
		return x.ListWrite
	}
	return nil
}

type SetWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdWriter      int32                  `protobuf:"varint,1,opt,name=id_writer,json=idWriter,proto3" json:"id_writer,omitempty"`
	IdSm          int32                  `protobuf:"varint,2,opt,name=id_sm,json=idSm,proto3" json:"id_sm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWrite) Reset() {
	*x = SetWrite{}
	mi := &file_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWrite) ProtoMessage() {}

func (x *SetWrite) ProtoReflect() protoreflect.Message {
	mi := &file_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWrite.ProtoReflect.Descriptor instead.
func (*SetWrite) Descriptor() ([]byte, []int) {
	return file_write_proto_rawDescGZIP(), []int{2}
}

func (x *SetWrite) GetIdWriter() int32 {
	if x != nil {
		return x.IdWriter
	}
	return 0
}

func (x *SetWrite) GetIdSm() int32 {
	if x != nil {
		return x.IdSm
	}
	return 0
}

var File_write_proto protoreflect.FileDescriptor

const file_write_proto_rawDesc = "" +
	"\n" +
	"\vwrite.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb4\x02\n" +
	"\fWriteService\x12\x1b\n" +
	"\tid_writer\x18\x01 \x01(\x05R\bidWriter\x12\x13\n" +
	"\x05id_sm\x18\x02 \x01(\x05R\x04idSm\x12\x13\n" +
	"\x05ip_db\x18\x03 \x01(\tR\x04ipDb\x12\x17\n" +
	"\aport_db\x18\x04 \x01(\x05R\x06portDb\x12\x17\n" +
	"\adb_name\x18\x05 \x01(\tR\x06dbName\x12\x19\n" +
	"\bdb_table\x18\x06 \x01(\tR\adbTable\x12\x14\n" +
	"\x05login\x18\a \x01(\tR\x05login\x12\x14\n" +
	"\x05passw\x18\b \x01(\tR\x05passw\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\v \x01(\bR\x06active\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\">\n" +
	"\bRetWrite\x122\n" +
	"\n" +
	"list_write\x18\x01 \x03(\v2\x13.proto.WriteServiceR\tlistWrite\"<\n" +
	"\bSetWrite\x12\x1b\n" +
	"\tid_writer\x18\x01 \x01(\x05R\bidWriter\x12\x13\n" +
	"\x05id_sm\x18\x02 \x01(\x05R\x04idSm2\x98\x02\n" +
	"\fWriteControl\x125\n" +
	"\n" +
	"ListWrites\x12\x16.google.protobuf.Empty\x1a\x0f.proto.RetWrite\x124\n" +
	"\bAddWrite\x12\x13.proto.WriteService\x1a\x13.proto.WriteService\x127\n" +
	"\vDeleteWrite\x12\x13.proto.WriteService\x1a\x13.proto.WriteService\x121\n" +
	"\tDownWrite\x12\x0f.proto.SetWrite\x1a\x13.proto.WriteService\x12/\n" +
	"\aUpWrite\x12\x0f.proto.SetWrite\x1a\x13.proto.WriteServiceB\x12Z\x10NavControl/protob\x06proto3"

var (
	file_write_proto_rawDescOnce sync.Once
	file_write_proto_rawDescData []byte
)

func file_write_proto_rawDescGZIP() []byte {
	file_write_proto_rawDescOnce.Do(func() {
		file_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_write_proto_rawDesc), len(file_write_proto_rawDesc)))
	})
	return file_write_proto_rawDescData
}

var file_write_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_write_proto_goTypes = []any{
	(*WriteService)(nil),  // 0: proto.WriteService
	(*RetWrite)(nil),      // 1: proto.RetWrite
	(*SetWrite)(nil),      // 2: proto.SetWrite
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_write_proto_depIdxs = []int32{
	0, // 0: proto.RetWrite.list_write:type_name -> proto.WriteService
	3, // 1: proto.WriteControl.ListWrites:input_type -> google.protobuf.Empty
	0, // 2: proto.WriteControl.AddWrite:input_type -> proto.WriteService
	0, // 3: proto.WriteControl.DeleteWrite:input_type -> proto.WriteService
	2, // 4: proto.WriteControl.DownWrite:input_type -> proto.SetWrite
	2, // 5: proto.WriteControl.UpWrite:input_type -> proto.SetWrite
	1, // 6: proto.WriteControl.ListWrites:output_type -> proto.RetWrite
	0, // 7: proto.WriteControl.AddWrite:output_type -> proto.WriteService
	0, // 8: proto.WriteControl.DeleteWrite:output_type -> proto.WriteService
	0, // 9: proto.WriteControl.DownWrite:output_type -> proto.WriteService
	0, // 10: proto.WriteControl.UpWrite:output_type -> proto.WriteService
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_write_proto_init() }
func file_write_proto_init() {
	if File_write_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_write_proto_rawDesc), len(file_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_write_proto_goTypes,
		DependencyIndexes: file_write_proto_depIdxs,
		MessageInfos:      file_write_proto_msgTypes,
	}.Build()
	File_write_proto = out.File
	file_write_proto_goTypes = nil
	file_write_proto_depIdxs = nil
}
